::call translate_json version_java id
::call translate_json version_java ja
::call translate_json version_java ru
::call translate_json version_java zh-cn
::call translate_json version_java de
::call translate_json version_java es
::call translate_json version_java fr
::call translate_json version_java ko
::call translate_json version_java it
::call translate_json version_java nl
::call translate_json version_java ro
::call translate_json version_java sk
::call translate_json version_java sl
::call translate_json version_java hi
::call translate_json version_java tr
::call translate_json version_java uk
::call translate_json version_java lv
::call translate_json version_java ms
