call translate_metadata_author_java_landings
call translate_metadata_category_java_landings
call translate_metadata_company_java_landings
call translate_metadata_createdtime_java_landings
call translate_metadata_description_java_landings
call translate_metadata_subject_java_landings
call translate_metadata_title_java_landings
call translate_metadata_version_java_landings