::call translate_json text_net de
::call translate_json text_net es
::call translate_json text_net fr
::call translate_json text_net id
::call translate_json text_net ja
::call translate_json text_net ko
::call translate_json text_net ru
::call translate_json text_net zh-cn
::call translate_json text_net it
::call translate_json text_net nl
::call translate_json text_net ro
::call translate_json text_net sk
::call translate_json text_net sl
::call translate_json text_net hi
::call translate_json text_net tr
::call translate_json text_net uk
::call translate_json text_net lv
::call translate_json text_net ms