::call translate_json subject_java id
::call translate_json subject_java ja
::call translate_json subject_java ru
::call translate_json subject_java zh-cn
::call translate_json subject_java de
::call translate_json subject_java es
::call translate_json subject_java fr
::call translate_json subject_java ko
::call translate_json subject_java it
::call translate_json subject_java nl
::call translate_json subject_java ro
::call translate_json subject_java sk
::call translate_json subject_java sl
::call translate_json subject_java hi
::call translate_json subject_java tr
::call translate_json subject_java uk
::call translate_json subject_java lv
::call translate_json subject_java ms
