::call translate_json annotation_net de
::call translate_json annotation_net es
::call translate_json annotation_net fr
::call translate_json annotation_net id
::call translate_json annotation_net ja
::call translate_json annotation_net ko
::call translate_json annotation_net ru
::call translate_json annotation_net zh-cn
::call translate_json annotation_net it
::call translate_json annotation_net nl
::call translate_json annotation_net ro
::call translate_json annotation_net sk
::call translate_json annotation_net sl
::call translate_json annotation_net hi
::call translate_json annotation_net tr
::call translate_json annotation_net uk
::call translate_json annotation_net lv
::call translate_json annotation_net ms