::call translate_json platform_index_net de
::call translate_json platform_index_net es
::call translate_json platform_index_net fr
::call translate_json platform_index_net id
::call translate_json platform_index_net ja
::call translate_json platform_index_net ko
::call translate_json platform_index_net ru
::call translate_json platform_index_net zh-cn
::call translate_json platform_index_net it
::call translate_json platform_index_net nl
::call translate_json platform_index_net ro
::call translate_json platform_index_net sk
::call translate_json platform_index_net sl
::call translate_json platform_index_net hi
::call translate_json platform_index_net tr
::call translate_json platform_index_net uk
::call translate_json platform_index_net lv
::call translate_json platform_index_net ms
