::call translate_json regex_java de
::call translate_json regex_java es
::call translate_json regex_java fr
::call translate_json regex_java id
::call translate_json regex_java ja
::call translate_json regex_java ko
::call translate_json regex_java ru
::call translate_json regex_java zh-cn
::call translate_json regex_java it
::call translate_json regex_java nl
::call translate_json regex_java ro
::call translate_json regex_java sk
::call translate_json regex_java sl
::call translate_json regex_java hi
::call translate_json regex_java tr
::call translate_json regex_java uk
::call translate_json regex_java lv
::call translate_json regex_java ms