::call translate_json description_net id
::call translate_json description_net ja
::call translate_json description_net ru
::call translate_json description_net zh-cn
::call translate_json description_net de
::call translate_json description_net es
::call translate_json description_net fr
::call translate_json description_net ko
::call translate_json description_net it
::call translate_json description_net nl
::call translate_json description_net ro
::call translate_json description_net sk
::call translate_json description_net sl
::call translate_json description_net hi
::call translate_json description_net tr
::call translate_json description_net uk
::call translate_json description_net lv
::call translate_json description_net ms
