inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [remove-sensitive-metadata]
- alias:  url
  values: [remove-sensitive-metadata]
- alias:  fileformat
  values: [pdf, docx, xlsx, pptx, jpeg, word, excel, powerpoint, image, photo]

generationRules:
  include:
  - fileformat[pdf, docx, xlsx, pptx, jpeg, word, excel, powerpoint, image, photo]
  
outputPath: "redaction\\{product}\\{url}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
