inherits: products.yml

dimensions: 
- alias: ext
  values: ["bmp", "doc", "docm", "docx", "dot", "dotm", "dotx", "pdf", "pot", "potm", "pps", "ppsm", "ppsx", "ppt", "pptm", "pptx", "rtf", "xls", "xlsm", "xlsx", "xlt", "xltm", "xltx"]

generationRules:
  exclude:
##    - ext[bmp, gif, jpeg, png, tiff]
  include:
##  - ext[odt]
    - lang[en, ko, ja, id, fr, es, de, ru, zh, it, nl, ro, sk, sl, hi, tr, uk, lv, ms]  

dictionaries: [ "..\\data\\description_{product}.{lang}.json", "..\\data\\description_{product}.json", "..\\data\\metadata_otherformats.json" ]

outputPath: "{product}\\metadata\\description\\{ext}.{lang}.md"