inherits: products.yml

dimensions: 
- alias: ext
  values: ["bmp", "csv", "doc", "docm", "docx", "dot", "dotm", "dotx", "gif",  "jpeg", "png", "pdf", "pot", "potm", "pps", "ppsm", "ppsx", "ppt", "pptm", "pptx", "rtf", "tiff", "xls", "xlsm", "xlsx", "xlt", "xltm", "xltx"]

generationRules:
  exclude:
##    - ext[bmp, gif, jpeg, png, tiff]
    - product[java]
  include:
##  - ext[odt]
    - lang[en, ko, ja, fr, es, de, ru, zh]  

dictionaries: [ "..\\data\\metadata_{product}.{lang}.json", "..\\data\\metadata_{product}.json", "..\\data\\metadata_otherformats.json" ]

outputPath: "{product}\\metadata\\{ext}.{lang}.md"