inherits: ..\\languages-index.yml

dimensions:  
- alias:  operation
  values: [index] 

- alias: product
  values: [java]

dictionaries: [ ..\\..\\data\\products.json ]

outputPath: "redaction\\{product}\\_index.{lang}.md"
