::call translate_json regex_net de
::call translate_json regex_net es
::call translate_json regex_net fr
::call translate_json regex_net id
::call translate_json regex_net ja
::call translate_json regex_net ko
::call translate_json regex_net ru
::call translate_json regex_net zh-cn
::call translate_json regex_net it
::call translate_json regex_net nl
::call translate_json regex_net ro
::call translate_json regex_net sk
::call translate_json regex_net sl
::call translate_json regex_net hi
::call translate_json regex_net tr
::call translate_json regex_net uk
::call translate_json regex_net lv
::call translate_json regex_net ms