::call translate_json description_java id
::call translate_json description_java ja
::call translate_json description_java ru
::call translate_json description_java zh-cn
::call translate_json description_java de
::call translate_json description_java es
::call translate_json description_java fr
::call translate_json description_java ko
::call translate_json description_java it
::call translate_json description_java nl
::call translate_json description_java ro
::call translate_json description_java sk
::call translate_json description_java sl
::call translate_json description_java hi
::call translate_json description_java tr
::call translate_json description_java uk
::call translate_json description_java lv
::call translate_json description_java ms
