::call translate_json author_net id
::call translate_json author_net ja
::call translate_json author_net ru
::call translate_json author_net zh-cn
::call translate_json author_net de
::call translate_json author_net es
::call translate_json author_net fr
::call translate_json author_net ko
::call translate_json author_net it
::call translate_json author_net nl
::call translate_json author_net ro
::call translate_json author_net sk
::call translate_json author_net sl
::call translate_json author_net hi
::call translate_json author_net tr
::call translate_json author_net uk
::call translate_json author_net lv
::call translate_json author_net ms
