::call translate_json text_java de
::call translate_json text_java es
::call translate_json text_java fr
::call translate_json text_java id
::call translate_json text_java ja
::call translate_json text_java ko
::call translate_json text_java ru
::call translate_json text_java zh-cn
::call translate_json text_java it
::call translate_json text_java nl
::call translate_json text_java ro
::call translate_json text_java sk
::call translate_json text_java sl
::call translate_json text_java hi
::call translate_json text_java tr
::call translate_json text_java uk
::call translate_json text_java lv
::call translate_json text_java ms