::call translate_json platform_index_java ru
::call translate_json platform_index_java bg
::call translate_json platform_index_java de
::call translate_json platform_index_java es
::call translate_json platform_index_java fr
::call translate_json platform_index_java id
::call translate_json platform_index_java it
::call translate_json platform_index_java ja
call translate_json platform_index_java ko
::call translate_json platform_index_java pl
::call translate_json platform_index_java pt
::call translate_json platform_index_java th
::call translate_json platform_index_java tr
::call translate_json platform_index_java vi
::call translate_json platform_index_java zh-cn