::call translate_json platform_index_net ru
::call translate_json platform_index_net bg
::call translate_json platform_index_net de
::call translate_json platform_index_net es
::call translate_json platform_index_net fr
::call translate_json platform_index_net id
::call translate_json platform_index_net it
call translate_json platform_index_net ja
::call translate_json platform_index_net ko
::call translate_json platform_index_net pl
::call translate_json platform_index_net pt
::call translate_json platform_index_net th
::call translate_json platform_index_net tr
::call translate_json platform_index_net vi
::call translate_json platform_index_net zh-cn