::call translate_json author_java id
::call translate_json author_java ja
::call translate_json author_java ru
::call translate_json author_java zh-cn
::call translate_json author_java de
::call translate_json author_java es
::call translate_json author_java fr
::call translate_json author_java ko
::call translate_json author_java it
::call translate_json author_java nl
::call translate_json author_java ro
::call translate_json author_java sk
::call translate_json author_java sl
::call translate_json author_java hi
::call translate_json author_java tr
::call translate_json author_java uk
::call translate_json author_java lv
::call translate_json author_java ms