::call translate_json annotation_java de
::call translate_json annotation_java es
::call translate_json annotation_java fr
::call translate_json annotation_java id
::call translate_json annotation_java ja
::call translate_json annotation_java ko
::call translate_json annotation_java ru
::call translate_json annotation_java zh-cn
::call translate_json annotation_java it
::call translate_json annotation_java nl
::call translate_json annotation_java ro
::call translate_json annotation_java sk
::call translate_json annotation_java sl
::call translate_json annotation_java hi
::call translate_json annotation_java tr
::call translate_json annotation_java uk
::call translate_json annotation_java lv
::call translate_json annotation_java ms