::call translate_json platform_index_java de
::call translate_json platform_index_java es
::call translate_json platform_index_java fr
::call translate_json platform_index_java id
::call translate_json platform_index_java ja
::call translate_json platform_index_java ko
::call translate_json platform_index_java ru
::call translate_json platform_index_java zh-cn
::call translate_json platform_index_java it
::call translate_json platform_index_java nl
::call translate_json platform_index_java ro
::call translate_json platform_index_java sk
::call translate_json platform_index_java sl
::call translate_json platform_index_java hi
::call translate_json platform_index_java tr
::call translate_json platform_index_java uk
::call translate_json platform_index_java lv
::call translate_json platform_index_java ms
